#!/usr/bin/env python
import os

REMOTE='/mnt/xcalibur'
DIRS_TO_SYNC=[	'Xcalibur/log',
				'Xcalibur/Service',
				'Xcalibur/CrysAlisINI',
			]
DATA_DIR='XcaliburData'
BACKUP='/media/usbdisk/xcalibur'

def rsync_dir(d):
	dir1 = os.path.join(REMOTE,d)
	dir2 = os.path.join(BACKUP,d)
	print 'rsync -av --exclude=tmp/ -n %s/ %s' %(dir1,dir2)
	os.system('rsync -av --exclude=tmp/ -n %s/ %s' %(dir1,dir2))
	doit = raw_input('This was DRY RUN!\nDo you want to run for real? [Yes,No]')
	if doit=='Yes':
	    os.system('rsync -av --exclude=tmp/  %s/ %s' %(dir1,dir2))
	else:
		pass
	
	
for d in DIRS_TO_SYNC:
	rsync_dir(d)

